"""empty message

Revision ID: 8b5b37bd2c51
Revises: 3d49fb2ffac4
Create Date: 2024-10-25 10:20:20.557189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b5b37bd2c51'
down_revision = '3d49fb2ffac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('japanfood', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('food',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('usafood', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('food',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usafood', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('food',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('japanfood', schema=None) as batch_op:
        batch_op.alter_column('link',
               existing_type=mysql.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('food',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
